name: App

include:
  - app/addons/addons.yml
packages:
  BareKit:
    url: https://github.com/holepunchto/bare-kit-swift
    branch: main
targets:
  App:
    type: application
    supportedDestinations: [iOS, macOS]
    deploymentTarget:
      iOS: 18.4
      macOS: 15.0

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Automatic

    info:
      path: app/Info.plist

    entitlements:
      path: app/App.entitlements
      properties:
        # com.apple.security.application-groups:
        #   - group.to.holepunch.bare.ios
        com.apple.security.cs.allow-jit: true

    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit

    sources:
      - path: app/App.swift
      - path: app/app.js
      - path: app/app.bundle
        optional: true

    scheme:
      preActions:
        - name: Link & Pack
          script: |
            case "$PLATFORM_NAME" in
              iphoneos|iphonesimulator)
                PRESET=ios
                ;;
              macosx)
                PRESET=darwin
                ;;
              *)
                PRESET=ios
                ;;
            esac

            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --preset ${PRESET} \
              --out ${PWD}/app/addons \
              ${PWD}

            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --preset ${PRESET} \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/app.js
